In [4]:
%pip install numpy

  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


In [6]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[ 4 25 15 11  3 20]
[[0 0 4]
 [8 1 8]]


In [7]:
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.74764873 0.42729531]
 [0.16404829 0.46841789]
 [0.71486158 0.56902945]]


In [9]:
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Banana' 'Banana']
['Banana' 'Orange' 'Apple']


In [10]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 2 3 4 5]
셔플본: [4 1 2 3 5]


In [11]:
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
uniform_data = rng.uniform(10.0, 20.0, size=5)
print(normal_data)
print(uniform_data)

[ 0.99728046 -0.05917118 -0.42205485 ...  0.28247912  1.34424929
  0.48917585]
[12.02937473 17.16896861 15.6882965  12.60497993 14.31101569]


In [13]:
np.random.rand(2,3)
arr2 = np.arange(16)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
arr2.shape

(16,)

In [17]:
arr2.dtype

dtype('int64')

In [18]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [19]:
np.save('array', arr)
load_arr = np.load('array.npy')
print(load_arr)


[1 2 3 4 5]


In [20]:
arr1 = np.arange(10)
arr2 = np.arange(20).reshape(4, 5)
arr3 = np.random.rand(3, 3)


In [24]:
np.savez('multiple_arrays', first_array=arr1, second_array=arr2, third_array=arr3)

In [25]:
loaded_data = np.load('multiple_arrays.npz')
print(loaded_data.files)
print(loaded_data['first_array'])
print(loaded_data['second_array'])
print(loaded_data['third_array'])


['first_array', 'second_array', 'third_array']
[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0.2208088  0.24010875 0.15023855]
 [0.94896153 0.78369931 0.40177422]
 [0.08156558 0.21194141 0.74631072]]


In [26]:
arr1_loaded = loaded_data['first_array']
arr2_loaded = loaded_data['second_array']   
arr3_loaded = loaded_data['third_array']

In [27]:
loaded_data.close()

In [28]:
np.savez_compressed('compressed_arrays', data1=arr1, data2=arr2, data3=arr3)
