In [1]:
#라이브러리 제거 
## 터미널: pip uninstall numpy
## 셀:%pip uninstall numpy
#실행 


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
%pip uninstall numpy -y

Found existing installation: numpy 2.4.6
Uninstalling numpy-2.4.6:
  Successfully uninstalled numpy-2.4.6
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
list_data = [1, 2, 3, 4]
result_list = []
for item in list_data:
    result_list.append(item*2)
print(result_list)
result_list    

[2, 4, 6, 8]


[2, 4, 6, 8]

In [ ]:
array_data = np.array([1,2,3,4])
result_array = array_data * 2
print(result_array)
result_array 

[2 4 6 8]


array([2, 4, 6, 8])

In [ ]:
line = [1, 2, 3]
arr1 = np.array(line)
arr1 

array([1, 2, 3])

In [ ]:
import time
start_time = time.time()
python_list = list(range(1000000))
result_list = [x*2 for x in python_list]
list_time = time.time()
print(f'리스트 연산 시간: {list_time:.2f}초')

리스트 연산 시간: 1782357135.04초


In [ ]:
start_time = time.time()
print(start_time)
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
print(result_array)
numpy_time = time.time() - start_time
print(f'NumPy 연산 시간: {numpy_time:.4f}초')
print(f'속도 개선: {list_time/numpy_time:.1f}배') 

1782357151.804134
[      0       2       4 ... 1999994 1999996 1999998]
NumPy 연산 시간: 0.0089초
속도 개선: 200137811178.3배


In [ ]:
list = [1, 2, 3]
arr1 = np.array(list)
arr2 = np.array([1, 2, 3])
arr3 = np.arange(10)
arr4 = np.arange(1, 10)
arr5 = np.arange(1, 10, 2)
arr6 = np.arange(10, 1, -1)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[1 2 3]
[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]


In [ ]:
import random
lotto_single = random.randint(1, 45)
print(lotto_single)

15


In [10]:
import random
even_num = random.randrange(0, 10, 2)
print(even_num)

8


In [11]:
prob = random.random()
print(prob)  # 예: 0.3547...

# 응용: 30% 확률 구현하기
if prob < 0.30:
    print("강화 성공!")
else:
    print("강화 실패...")


0.6380327300103869
강화 실패...


In [12]:
print(random.uniform(1.5, 5.5))

2.838947224820568


In [13]:
numbers = list(range(1, 46))
# 1~45 중에서 중복 없이 6개 번호 추첨
lotto_numbers = random.sample(numbers, 6)
print(lotto_numbers)  # 보기 좋게 정렬해서 출력

[24, 38, 19, 4, 40, 28]


In [14]:
cards = ["A", "K", "Q", "J"]
random.shuffle(cards)
print(cards)  # 원본 순서가 뒤섞인 결과 출력 (예: ['Q', 'A', 'J', 'K'])

['J', 'K', 'Q', 'A']
