In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
arr2 = np.arange(16).reshape(4, 4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
print(arr2[1]) 
print(arr2[1][1])  # Accessing a specific element

[4 5 6 7]
5


In [7]:
arr2[1, 2] = 100
print(arr2)

[[  0   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [8]:
print(arr2[0:2, 2:4])
print(arr2[:2, 2:])  # Slicing the array


[[  2   3]
 [100   7]]
[[  2   3]
 [100   7]]
