In [1]:
import numpy as np

arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [2]:
arr + 2

array([3, 4, 5, 6])

In [3]:
arr * 2

array([2, 4, 6, 8])

In [4]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [5]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [7]:
arr + arr1

array([ 6,  8, 10, 12])

In [8]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
print(np.square(arr))
print(np.sqrt(arr))
print(np.exp(arr))  
print(np.log(arr)) 

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [10]:
print(np.mean(arr)) 
print(np.var(arr))   
print(np.std(arr)) 
print(np.min(arr)) 
print(np.max(arr))   
print(np.argmin(arr))
print(np.argmax(arr))

2.5
1.25
1.118033988749895
1
4
0
3


In [11]:
arr = np.arange(10).reshape(2, 5)
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
print(arr.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [13]:
print(arr.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [14]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
print(arr.transpose())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [16]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [17]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr_2d, axis=0))
print(np.sum(arr_2d, axis=1))
print(np.sum(arr_2d))  


[5 7 9]
[ 6 15]
21


In [18]:
arr = np.array([1, -2, 3, -4, 5])
print(np.abs(arr))
result = np.where(arr > 0, arr, 0)
print(result)

[1 2 3 4 5]
[1 0 3 0 5]


In [19]:
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
prices = np.array([100, 102, 98, 105, 103, 99, 101])
def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')
ma_3 = moving_average(prices, 3)
print(ma_3)
    
